### ISSUE TITLE
Compatible with Relay?

### ISSUE THREAD

**Issue by Anahkiasen** [franzliedke/whoops-middleware#1]
Is there any way to make this compatible with [Relay](https://github.com/relayphp/Relay.Relay)?

**Comment by franzliedke** [comment]
I think so: Let me try to build an alternative middleware with the classical interface with a try/catch block.

**Comment by franzliedke** [comment]
Relay should now be supported in [v0.2.0](https://github.com/franzliedke/whoops-middleware/releases/tag/0.2.0). Please try it out and report back. :)

**Comment by Anahkiasen** [comment]
Works perfectly!

**Comment by franzliedke** [comment]
:)
