### ISSUE TITLE
Drop requirement for zendframework/zend-diactoros

### ISSUE THREAD

**Issue by shadowhand** [franzliedke/whoops-middleware#12]
There's no need for this requirement. I am using Slim and already have a PSR-7 implementation.

**Comment by franzliedke** [comment]
So you're proposing to adopt PSR-17 factories, I assume?

I'm currently using Diactoros here: https://github.com/franzliedke/whoops-middleware/blob/040df4c8b59fdf0e4def28810d97b5a3723c5e92/src/WhoopsRunner.php#L26-L30

**Comment by shadowhand** [comment]
Yes, PSR-15 factories would be a good solution.

**Comment by raghuveer** [comment]
using PSR-7 Diactoros library is good, I too use that, but I would request you to replace zendframework/zend-diactoros with laminas/laminas-diactoros instead in the composer based dependencies list.

Coming to PSR-15 library, laminas/laminas-stratigility is good like many other PSR-15 Dispatchers.

thank you

**Comment by franzliedke** [comment]
This has been done with #13 or, more precisely, commit 71d75c5fff75587d6194a051d510a9eca0e3a047.

@shadowhand Please let me know whether this change does the trick for you. [Released as version 2.0](https://github.com/franzliedke/whoops-middleware/releases/tag/2.0.0). Happy new year! :smiley:
