### ISSUE TITLE
Conflicts with Whoops 2.x

### ISSUE THREAD

**Issue by jimbojsb** [franzliedke/whoops-middleware#2]
Not sure if this is actually incompatible, but the composer.json requires 1.1 and 2.0 is out now.

**Comment by franzliedke** [comment]
Howdy. :)

I'm currently investigating the difference between the major versions. If the only BC break is the supported PHP version (it seems so), I will update the version constraint and release a new version.

**Comment by franzliedke** [comment]
And done. Check out [v0.3.0](https://github.com/franzliedke/whoops-middleware/releases/tag/0.3.0).

**Comment by franzliedke** [comment]
Also, see https://github.com/filp/whoops/issues/356#issuecomment-176649047.
